title: Vidit Maniyar's Work in Press # The title of the blog
author: Vidit Maniyar # Your name
email: your-email@domain.com # your email shown in the footer
url: https://viditmaniyar.github.io # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  A clean and minimalist theme for Jekyll.
favicon: "./favicon.ico" # set the favicon of the site
show_excerpts: false # set to true to show excerpts on the homepage

moving:
  avatar_url: "https://avatars.githubusercontent.com/u/12117759?s=400&u=f55d230262ac00473995d18731f40155cc12d1ae&v=4" # avatar in about page
  about_you: a short description about you. # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: viditmaniyar
    # github: viditmaniyar
    # rss: RSS
    # dribbble:
    # facebook: viditmaniyar
    # flickr:
    # instagram: viditmaniyar
    linkedin: viditmaniyar
    # pinterest:
    youtube: viditmaniyar
    # youtube_channel:
    # youtube_channel_name:
    # telegram:
    # googleplus:
    # microdotblog:
    # reddit:

# Build settings
# theme: moving
# remote_theme: huangyz0918/moving

plugins:
  - jekyll-feed
  - jekyll-seo-tag
