title: Vidit Maniyar # name of the site
author: Vidit Maniyar # name of site's author
email: viditmaniyar@gmail.com # email of site's author
url: https://viditmaniyar.github.io/ # root address of the site
postnominals: FRSA, Senior Member IEEE
description: Software Engineer @ Meta, working on WhatsApp

favicon: "./logo.png" # relative path to site's favicon

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # switch dark/light mode
  back_home_text: "← home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

plugins:
  - jekyll-feed
  - jekyll-seo-tag
